openapi: 3.0.0
info:
  title: Expense Tracker
  version: 1.0.0
  description: A project which tracks the expense
servers:
  - url: /api/v1/admin/
    description: Local server
paths:
  /register:
    post:
      summary: Register a new admin
      description: Register a new admin with the required details.
      tags:
        - Admin
      requestBody:
        description: Admin registration details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin
                email:
                  type: string
                  example: admin@example.com
                password:
                  type: string
                  example: password123
      responses:
        '200':
          description: Admin registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Admin registered successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /login:
    post:
      summary: Login an admin
      description: Login an admin with email and password.
      tags:
        - Admin
      requestBody:
        description: Admin login details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: admin@example.com
                password:
                  type: string
                  example: password123
      responses:
        '200':
          description: Admin logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Admin logged in successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /logout:
    post:
      summary: Logout an admin
      description: Logout an admin with email and password.
      tags:
        - Admin
      responses:
        '200':
          description: Admin logged out in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Admin logged in successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /users/createUser:
    post:
      summary: Create a new user
      description: Create a new user with the required details. Requires admin authentication.
      tags:
        - User
      security:
        - bearerAuth: []
      requestBody:
        description: User creation details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                empId:
                  type: string
                  example: 1000
                userName:
                  type: string
                  example: John Wick
                email:
                  type: string
                  example: jhonwick@gmail.com
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User created successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /users/getUsers:
    get:
      summary: Get all users
      description: Retrieve a list of all users with pagination. Requires admin authentication.
      tags:
        - User
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number for pagination
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Number of users to return per page
      responses:
        '200':
          description: Successfully retrieved list of users
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: number
                    example: 5
                  limit:
                    type: number
                    example: 1
                  totalUsers:
                    type: number
                    example: 4
                  totalPages:
                    type: number
                    example: 6
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          example: 60d0fe4f5311236168a109ca
                        empId:
                          type: string
                          example: 1000
                        userName:
                          type: string
                          example: John Doe
                        email:
                          type: string
                          example: johndoe@example.com
                        createdAt:
                          type: string
                          format: date-time
                        updatedAt:
                          type: string
                          format: date-time
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
